/****************************************************************************
**
** Metadata for OmniRig generated by dumpcpp v6.6.3 using
** from the type library OmniRig.exe
**
****************************************************************************/

#include "omnirig.h"
#if defined _WIN32_
#define QAX_DUMPCPP_OMNIRIG_NOINLINES

using namespace OmniRig;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[130];
    char stringdata0[1250];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 18, 0),
QT_MOC_LITERAL(1, 19, 9, 0),
QT_MOC_LITERAL(2, 29, 0, 0),
QT_MOC_LITERAL(3, 30, 4, 0),
QT_MOC_LITERAL(4, 35, 6, 0),
QT_MOC_LITERAL(5, 42, 4, 0),
QT_MOC_LITERAL(6, 47, 4, 0),
QT_MOC_LITERAL(7, 52, 15, 0),
QT_MOC_LITERAL(8, 68, 4, 0),
QT_MOC_LITERAL(9, 73, 6, 0),
QT_MOC_LITERAL(10, 80, 4, 0),
QT_MOC_LITERAL(11, 85, 4, 0),
QT_MOC_LITERAL(12, 90, 16, 0),
QT_MOC_LITERAL(13, 107, 13, 0),
QT_MOC_LITERAL(14, 121, 16, 0),
QT_MOC_LITERAL(15, 138, 4, 0),
QT_MOC_LITERAL(16, 143, 6, 0),
QT_MOC_LITERAL(17, 150, 4, 0),
QT_MOC_LITERAL(18, 155, 15, 0),
QT_MOC_LITERAL(19, 171, 7, 0),
QT_MOC_LITERAL(20, 179, 9, 0),
QT_MOC_LITERAL(21, 189, 10, 0),
QT_MOC_LITERAL(22, 200, 7, 0),
QT_MOC_LITERAL(23, 208, 8, 0),
QT_MOC_LITERAL(24, 217, 8, 0),
QT_MOC_LITERAL(25, 226, 8, 0),
QT_MOC_LITERAL(26, 235, 12, 0),
QT_MOC_LITERAL(27, 248, 7, 0),
QT_MOC_LITERAL(28, 256, 8, 0),
QT_MOC_LITERAL(29, 265, 8, 0),
QT_MOC_LITERAL(30, 274, 8, 0),
QT_MOC_LITERAL(31, 283, 8, 0),
QT_MOC_LITERAL(32, 292, 7, 0),
QT_MOC_LITERAL(33, 300, 7, 0),
QT_MOC_LITERAL(34, 308, 11, 0),
QT_MOC_LITERAL(35, 320, 10, 0),
QT_MOC_LITERAL(36, 331, 10, 0),
QT_MOC_LITERAL(37, 342, 11, 0),
QT_MOC_LITERAL(38, 354, 8, 0),
QT_MOC_LITERAL(39, 363, 9, 0),
QT_MOC_LITERAL(40, 373, 8, 0),
QT_MOC_LITERAL(41, 382, 9, 0),
QT_MOC_LITERAL(42, 392, 5, 0),
QT_MOC_LITERAL(43, 398, 5, 0),
QT_MOC_LITERAL(44, 404, 7, 0),
QT_MOC_LITERAL(45, 412, 7, 0),
QT_MOC_LITERAL(46, 420, 8, 0),
QT_MOC_LITERAL(47, 429, 8, 0),
QT_MOC_LITERAL(48, 438, 8, 0),
QT_MOC_LITERAL(49, 447, 8, 0),
QT_MOC_LITERAL(50, 456, 5, 0),
QT_MOC_LITERAL(51, 462, 5, 0),
QT_MOC_LITERAL(52, 468, 10, 0),
QT_MOC_LITERAL(53, 479, 16, 0),
QT_MOC_LITERAL(54, 496, 11, 0),
QT_MOC_LITERAL(55, 508, 11, 0),
QT_MOC_LITERAL(56, 520, 16, 0),
QT_MOC_LITERAL(57, 537, 9, 0),
QT_MOC_LITERAL(58, 547, 17, 0),
QT_MOC_LITERAL(59, 565, 17, 0),
QT_MOC_LITERAL(60, 583, 15, 0),
QT_MOC_LITERAL(61, 599, 11, 0),
QT_MOC_LITERAL(62, 611, 9, 0),
QT_MOC_LITERAL(63, 621, 11, 0),
QT_MOC_LITERAL(64, 633, 9, 0),
QT_MOC_LITERAL(65, 643, 7, 0),
QT_MOC_LITERAL(66, 651, 5, 0),
QT_MOC_LITERAL(67, 657, 12, 0),
QT_MOC_LITERAL(68, 670, 6, 0),
QT_MOC_LITERAL(69, 677, 13, 0),
QT_MOC_LITERAL(70, 691, 12, 0),
QT_MOC_LITERAL(71, 704, 13, 0),
QT_MOC_LITERAL(72, 718, 14, 0),
QT_MOC_LITERAL(73, 733, 8, 0),
QT_MOC_LITERAL(74, 742, 15, 0),
QT_MOC_LITERAL(75, 758, 4, 0),
QT_MOC_LITERAL(76, 763, 14, 0),
QT_MOC_LITERAL(77, 778, 14, 0),
QT_MOC_LITERAL(78, 793, 15, 0),
QT_MOC_LITERAL(79, 809, 5, 0),
QT_MOC_LITERAL(80, 815, 16, 0),
QT_MOC_LITERAL(81, 832, 17, 0),
QT_MOC_LITERAL(82, 850, 11, 0),
QT_MOC_LITERAL(83, 862, 8, 0),
QT_MOC_LITERAL(84, 871, 7, 0),
QT_MOC_LITERAL(85, 879, 4, 0),
QT_MOC_LITERAL(86, 884, 8, 0),
QT_MOC_LITERAL(87, 893, 5, 0),
QT_MOC_LITERAL(88, 899, 8, 0),
QT_MOC_LITERAL(89, 908, 5, 0),
QT_MOC_LITERAL(90, 914, 7, 0),
QT_MOC_LITERAL(91, 922, 4, 0),
QT_MOC_LITERAL(92, 927, 8, 0),
QT_MOC_LITERAL(93, 936, 5, 0),
QT_MOC_LITERAL(94, 942, 6, 0),
QT_MOC_LITERAL(95, 949, 3, 0),
QT_MOC_LITERAL(96, 953, 12, 0),
QT_MOC_LITERAL(97, 966, 9, 0),
QT_MOC_LITERAL(98, 976, 14, 0),
QT_MOC_LITERAL(99, 991, 8, 0),
QT_MOC_LITERAL(100, 1000, 5, 0),
QT_MOC_LITERAL(101, 1006, 12, 0),
QT_MOC_LITERAL(102, 1019, 6, 0),
QT_MOC_LITERAL(103, 1026, 6, 0),
QT_MOC_LITERAL(104, 1033, 5, 0),
QT_MOC_LITERAL(105, 1039, 2, 0),
QT_MOC_LITERAL(106, 1042, 6, 0),
QT_MOC_LITERAL(107, 1049, 3, 0),
QT_MOC_LITERAL(108, 1053, 6, 0),
QT_MOC_LITERAL(109, 1060, 3, 0),
QT_MOC_LITERAL(110, 1064, 8, 0),
QT_MOC_LITERAL(111, 1073, 10, 0),
QT_MOC_LITERAL(112, 1084, 14, 0),
QT_MOC_LITERAL(113, 1099, 7, 0),
QT_MOC_LITERAL(114, 1107, 6, 0),
QT_MOC_LITERAL(115, 1114, 9, 0),
QT_MOC_LITERAL(116, 1124, 15, 0),
QT_MOC_LITERAL(117, 1140, 13, 0),
QT_MOC_LITERAL(118, 1154, 5, 0),
QT_MOC_LITERAL(119, 1160, 18, 0),
QT_MOC_LITERAL(120, 1179, 4, 0),
QT_MOC_LITERAL(121, 1184, 6, 0),
QT_MOC_LITERAL(122, 1191, 3, 0),
QT_MOC_LITERAL(123, 1195, 6, 0),
QT_MOC_LITERAL(124, 1202, 3, 0),
QT_MOC_LITERAL(125, 1206, 6, 0),
QT_MOC_LITERAL(126, 1213, 3, 0),
QT_MOC_LITERAL(127, 1217, 3, 0),
QT_MOC_LITERAL(128, 1221, 17, 0),
QT_MOC_LITERAL(129, 1239, 9, 0)
    },
    "OmniRig::IOmniRigX\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0"
    "signal\0argc\0argv\0SetDialogVisible\0DialogVisible\0InterfaceVersion\0Rig1\0IRigX*\0"
    "Rig2\0SoftwareVersion\0control\0RigParamX\0PM_UNKNOWN\0PM_FREQ\0PM_FREQA\0PM_FREQB\0"
    "PM_PITCH\0PM_RITOFFSET\0PM_RIT0\0PM_VFOAA\0PM_VFOAB\0PM_VFOBA\0PM_VFOBB\0PM_VFOA\0"
    "PM_VFOB\0PM_VFOEQUAL\0PM_VFOSWAP\0PM_SPLITON\0PM_SPLITOFF\0PM_RITON\0PM_RITOFF\0"
    "PM_XITON\0PM_XITOFF\0PM_RX\0PM_TX\0PM_CW_U\0PM_CW_L\0PM_SSB_U\0PM_SSB_L\0PM_DIG_U\0"
    "PM_DIG_L\0PM_AM\0PM_FM\0RigStatusX\0ST_NOTCONFIGURED\0ST_DISABLED\0ST_PORTBUSY\0"
    "ST_NOTRESPONDING\0ST_ONLINE\0OmniRig::OmniRigX\0Event Interface 1\0IOmniRigXEvents\0"
    "Interface 0\0IOmniRigX\0CustomReply\0RigNumber\0Command\0Reply\0ParamsChange\0Params\0"
    "RigTypeChange\0StatusChange\0VisibleChange\0OmniRig::IRigX\0ClearRit\0FrequencyOfTone\0"
    "Tone\0GetRxFrequency\0GetTxFrequency\0IsParamReadable\0Param\0IsParamWriteable\0"
    "SendCustomCommand\0ReplyLength\0ReplyEnd\0SetFreq\0Freq\0SetFreqA\0FreqA\0SetFreqB\0"
    "FreqB\0SetMode\0Mode\0SetPitch\0Pitch\0SetRit\0Rit\0SetRitOffset\0RitOffset\0"
    "SetSimplexMode\0SetSplit\0Split\0SetSplitMode\0RxFreq\0TxFreq\0SetTx\0Tx\0SetVfo\0Vfo\0"
    "SetXit\0Xit\0PortBits\0IPortBits*\0ReadableParams\0RigType\0Status\0StatusStr\0"
    "WriteableParams\0OmniRig::RigX\0IRigX\0OmniRig::IPortBits\0Lock\0SetDtr\0Dtr\0SetRts\0"
    "Rts\0Unlock\0Cts\0Dsr\0OmniRig::PortBits\0IPortBits\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_OmniRig__IOmniRigX[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    4, 14, // methods
    6, 56, // properties
    2, 74, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 34, 2, 5,
    7, 1, 43, 2, 5,
    9, 3, 46, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 53, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 13,

 // properties: name, type, flags
    13, QMetaType::Bool, 0x01015003, 		 // bool DialogVisible
    14, QMetaType::Int, 0x02005001, 		 // int InterfaceVersion
    15, 0x80000000 | 16, 0x00005001, 		 // IRigX* Rig1
    17, 0x80000000 | 16, 0x00005001, 		 // IRigX* Rig2
    18, QMetaType::Int, 0x02005001, 		 // int SoftwareVersion
    19, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    20, 0x0, 31, 82, 
    52, 0x0, 5, 144, 

 // enum data: key, value
    21, uint(OmniRig::PM_UNKNOWN),
    22, uint(OmniRig::PM_FREQ),
    23, uint(OmniRig::PM_FREQA),
    24, uint(OmniRig::PM_FREQB),
    25, uint(OmniRig::PM_PITCH),
    26, uint(OmniRig::PM_RITOFFSET),
    27, uint(OmniRig::PM_RIT0),
    28, uint(OmniRig::PM_VFOAA),
    29, uint(OmniRig::PM_VFOAB),
    30, uint(OmniRig::PM_VFOBA),
    31, uint(OmniRig::PM_VFOBB),
    32, uint(OmniRig::PM_VFOA),
    33, uint(OmniRig::PM_VFOB),
    34, uint(OmniRig::PM_VFOEQUAL),
    35, uint(OmniRig::PM_VFOSWAP),
    36, uint(OmniRig::PM_SPLITON),
    37, uint(OmniRig::PM_SPLITOFF),
    38, uint(OmniRig::PM_RITON),
    39, uint(OmniRig::PM_RITOFF),
    40, uint(OmniRig::PM_XITON),
    41, uint(OmniRig::PM_XITOFF),
    42, uint(OmniRig::PM_RX),
    43, uint(OmniRig::PM_TX),
    44, uint(OmniRig::PM_CW_U),
    45, uint(OmniRig::PM_CW_L),
    46, uint(OmniRig::PM_SSB_U),
    47, uint(OmniRig::PM_SSB_L),
    48, uint(OmniRig::PM_DIG_U),
    49, uint(OmniRig::PM_DIG_L),
    50, uint(OmniRig::PM_AM),
    51, uint(OmniRig::PM_FM),
    53, uint(OmniRig::ST_NOTCONFIGURED),
    54, uint(OmniRig::ST_DISABLED),
    55, uint(OmniRig::ST_PORTBUSY),
    56, uint(OmniRig::ST_NOTRESPONDING),
    57, uint(OmniRig::ST_ONLINE),
    0 // eod
};

const QMetaObject IOmniRigX::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OmniRig__IOmniRigX, 0, 0, 0 }
};

void *IOmniRigX::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OmniRig::IOmniRigX"))
        return static_cast<void*>(const_cast<IOmniRigX*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_OmniRig__OmniRigX[] = {

 // content:
    7, // revision
    58,  // classname
    2, 14, // classinfo
    9, 18, // methods
    5, 104, // properties
    2, 119, // enums/sets
    0, 0, // constructors
    0, // flags
    8, // signal count

 // classinfo: key, value
    59, 60, 
    61, 62, 

// signal: name, argc, parameters, tag, flags
    63, 3, 63, 2, 5,
    67, 2, 70, 2, 5,
    69, 1, 75, 2, 5,
    70, 1, 78, 2, 5,
    71, 0, 81, 2, 5,
    1, 4, 82, 2, 5,
    7, 1, 91, 2, 5,
    9, 3, 94, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 101, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QVariant, QMetaType::QVariant, 64, 65, 66,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 64, 68,
    QMetaType::Void, QMetaType::Int, 64,
    QMetaType::Void, QMetaType::Int, 64,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 13,

 // properties: name, type, flags
    13, QMetaType::Bool, 0x01015003, 		 // bool DialogVisible
    14, QMetaType::Int, 0x02005001, 		 // int InterfaceVersion
    15, 0x80000000 | 16, 0x00005001, 		 // IRigX* Rig1
    17, 0x80000000 | 16, 0x00005001, 		 // IRigX* Rig2
    18, QMetaType::Int, 0x02005001, 		 // int SoftwareVersion

 // enums: name, flags, count, data
    20, 0x0, 31, 127, 
    52, 0x0, 5, 189, 

 // enum data: key, value
    21, uint(OmniRig::PM_UNKNOWN),
    22, uint(OmniRig::PM_FREQ),
    23, uint(OmniRig::PM_FREQA),
    24, uint(OmniRig::PM_FREQB),
    25, uint(OmniRig::PM_PITCH),
    26, uint(OmniRig::PM_RITOFFSET),
    27, uint(OmniRig::PM_RIT0),
    28, uint(OmniRig::PM_VFOAA),
    29, uint(OmniRig::PM_VFOAB),
    30, uint(OmniRig::PM_VFOBA),
    31, uint(OmniRig::PM_VFOBB),
    32, uint(OmniRig::PM_VFOA),
    33, uint(OmniRig::PM_VFOB),
    34, uint(OmniRig::PM_VFOEQUAL),
    35, uint(OmniRig::PM_VFOSWAP),
    36, uint(OmniRig::PM_SPLITON),
    37, uint(OmniRig::PM_SPLITOFF),
    38, uint(OmniRig::PM_RITON),
    39, uint(OmniRig::PM_RITOFF),
    40, uint(OmniRig::PM_XITON),
    41, uint(OmniRig::PM_XITOFF),
    42, uint(OmniRig::PM_RX),
    43, uint(OmniRig::PM_TX),
    44, uint(OmniRig::PM_CW_U),
    45, uint(OmniRig::PM_CW_L),
    46, uint(OmniRig::PM_SSB_U),
    47, uint(OmniRig::PM_SSB_L),
    48, uint(OmniRig::PM_DIG_U),
    49, uint(OmniRig::PM_DIG_L),
    50, uint(OmniRig::PM_AM),
    51, uint(OmniRig::PM_FM),
    53, uint(OmniRig::ST_NOTCONFIGURED),
    54, uint(OmniRig::ST_DISABLED),
    55, uint(OmniRig::ST_PORTBUSY),
    56, uint(OmniRig::ST_NOTRESPONDING),
    57, uint(OmniRig::ST_ONLINE),
    0 // eod
};

const QMetaObject OmniRigX::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OmniRig__OmniRigX, 0, 0, 0 }
};

void *OmniRigX::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OmniRig::OmniRigX"))
        return static_cast<void*>(const_cast<OmniRigX*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_OmniRig__IRigX[] = {

 // content:
    7, // revision
    72,  // classname
    0, 0, // classinfo
    23, 14, // methods
    18, 208, // properties
    2, 262, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 129, 2, 5,
    7, 1, 138, 2, 5,
    9, 3, 141, 2, 5,

// slot: name, argc, parameters, tag, flags
    73, 0, 148, 2, 9,
    74, 1, 149, 2, 9,
    76, 0, 152, 2, 9,
    77, 0, 153, 2, 9,
    78, 1, 154, 2, 9,
    80, 1, 157, 2, 9,
    81, 3, 160, 2, 9,
    84, 1, 167, 2, 9,
    86, 1, 170, 2, 9,
    88, 1, 173, 2, 9,
    90, 1, 176, 2, 9,
    92, 1, 179, 2, 9,
    94, 1, 182, 2, 9,
    96, 1, 185, 2, 9,
    98, 1, 188, 2, 9,
    99, 1, 191, 2, 9,
    101, 2, 194, 2, 9,
    104, 1, 199, 2, 9,
    106, 1, 202, 2, 9,
    108, 1, 205, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 75,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Bool, 0x80000000 | 20, 79,
    QMetaType::Bool, 0x80000000 | 20, 79,
    QMetaType::Void, QMetaType::QVariant, QMetaType::Int, QMetaType::QVariant, 65, 82, 83,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, 0x80000000 | 20, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, 0x80000000 | 20, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, 0x80000000 | 20, 100,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 102, 103,
    QMetaType::Void, 0x80000000 | 20, 105,
    QMetaType::Void, 0x80000000 | 20, 107,
    QMetaType::Void, 0x80000000 | 20, 109,

 // properties: name, type, flags
    85, QMetaType::Int, 0x02015003, 		 // int Freq
    87, QMetaType::Int, 0x02015003, 		 // int FreqA
    89, QMetaType::Int, 0x02015003, 		 // int FreqB
    91, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Mode
    93, QMetaType::Int, 0x02015003, 		 // int Pitch
    110, 0x80000000 | 111, 0x00005001, 		 // IPortBits* PortBits
    112, QMetaType::Int, 0x02005001, 		 // int ReadableParams
    113, QMetaType::QString, 0x0a005001, 		 // QString RigType
    95, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Rit
    97, QMetaType::Int, 0x02015003, 		 // int RitOffset
    100, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Split
    114, 0x80000000 | 52, 0x02005009, 		 // RigStatusX Status
    115, QMetaType::QString, 0x0a005001, 		 // QString StatusStr
    105, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Tx
    107, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Vfo
    116, QMetaType::Int, 0x02005001, 		 // int WriteableParams
    109, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Xit
    19, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    20, 0x0, 31, 270, 
    52, 0x0, 5, 332, 

 // enum data: key, value
    21, uint(OmniRig::PM_UNKNOWN),
    22, uint(OmniRig::PM_FREQ),
    23, uint(OmniRig::PM_FREQA),
    24, uint(OmniRig::PM_FREQB),
    25, uint(OmniRig::PM_PITCH),
    26, uint(OmniRig::PM_RITOFFSET),
    27, uint(OmniRig::PM_RIT0),
    28, uint(OmniRig::PM_VFOAA),
    29, uint(OmniRig::PM_VFOAB),
    30, uint(OmniRig::PM_VFOBA),
    31, uint(OmniRig::PM_VFOBB),
    32, uint(OmniRig::PM_VFOA),
    33, uint(OmniRig::PM_VFOB),
    34, uint(OmniRig::PM_VFOEQUAL),
    35, uint(OmniRig::PM_VFOSWAP),
    36, uint(OmniRig::PM_SPLITON),
    37, uint(OmniRig::PM_SPLITOFF),
    38, uint(OmniRig::PM_RITON),
    39, uint(OmniRig::PM_RITOFF),
    40, uint(OmniRig::PM_XITON),
    41, uint(OmniRig::PM_XITOFF),
    42, uint(OmniRig::PM_RX),
    43, uint(OmniRig::PM_TX),
    44, uint(OmniRig::PM_CW_U),
    45, uint(OmniRig::PM_CW_L),
    46, uint(OmniRig::PM_SSB_U),
    47, uint(OmniRig::PM_SSB_L),
    48, uint(OmniRig::PM_DIG_U),
    49, uint(OmniRig::PM_DIG_L),
    50, uint(OmniRig::PM_AM),
    51, uint(OmniRig::PM_FM),
    53, uint(OmniRig::ST_NOTCONFIGURED),
    54, uint(OmniRig::ST_DISABLED),
    55, uint(OmniRig::ST_PORTBUSY),
    56, uint(OmniRig::ST_NOTRESPONDING),
    57, uint(OmniRig::ST_ONLINE),
    0 // eod
};

const QMetaObject IRigX::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OmniRig__IRigX, 0, 0, 0 }
};

void *IRigX::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OmniRig::IRigX"))
        return static_cast<void*>(const_cast<IRigX*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_OmniRig__RigX[] = {

 // content:
    7, // revision
    117,  // classname
    1, 14, // classinfo
    23, 16, // methods
    17, 210, // properties
    2, 261, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    61, 118, 

// signal: name, argc, parameters, tag, flags
    1, 4, 131, 2, 5,
    7, 1, 140, 2, 5,
    9, 3, 143, 2, 5,

// slot: name, argc, parameters, tag, flags
    73, 0, 150, 2, 9,
    74, 1, 151, 2, 9,
    76, 0, 154, 2, 9,
    77, 0, 155, 2, 9,
    78, 1, 156, 2, 9,
    80, 1, 159, 2, 9,
    81, 3, 162, 2, 9,
    84, 1, 169, 2, 9,
    86, 1, 172, 2, 9,
    88, 1, 175, 2, 9,
    90, 1, 178, 2, 9,
    92, 1, 181, 2, 9,
    94, 1, 184, 2, 9,
    96, 1, 187, 2, 9,
    98, 1, 190, 2, 9,
    99, 1, 193, 2, 9,
    101, 2, 196, 2, 9,
    104, 1, 201, 2, 9,
    106, 1, 204, 2, 9,
    108, 1, 207, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 75,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Bool, 0x80000000 | 20, 79,
    QMetaType::Bool, 0x80000000 | 20, 79,
    QMetaType::Void, QMetaType::QVariant, QMetaType::Int, QMetaType::QVariant, 65, 82, 83,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, 0x80000000 | 20, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, 0x80000000 | 20, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, 0x80000000 | 20, 100,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 102, 103,
    QMetaType::Void, 0x80000000 | 20, 105,
    QMetaType::Void, 0x80000000 | 20, 107,
    QMetaType::Void, 0x80000000 | 20, 109,

 // properties: name, type, flags
    85, QMetaType::Int, 0x02015003, 		 // int Freq
    87, QMetaType::Int, 0x02015003, 		 // int FreqA
    89, QMetaType::Int, 0x02015003, 		 // int FreqB
    91, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Mode
    93, QMetaType::Int, 0x02015003, 		 // int Pitch
    110, 0x80000000 | 111, 0x00005001, 		 // IPortBits* PortBits
    112, QMetaType::Int, 0x02005001, 		 // int ReadableParams
    113, QMetaType::QString, 0x0a005001, 		 // QString RigType
    95, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Rit
    97, QMetaType::Int, 0x02015003, 		 // int RitOffset
    100, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Split
    114, 0x80000000 | 52, 0x02005009, 		 // RigStatusX Status
    115, QMetaType::QString, 0x0a005001, 		 // QString StatusStr
    105, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Tx
    107, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Vfo
    116, QMetaType::Int, 0x02005001, 		 // int WriteableParams
    109, 0x80000000 | 20, 0x0201500b, 		 // RigParamX Xit

 // enums: name, flags, count, data
    20, 0x0, 31, 269, 
    52, 0x0, 5, 331, 

 // enum data: key, value
    21, uint(OmniRig::PM_UNKNOWN),
    22, uint(OmniRig::PM_FREQ),
    23, uint(OmniRig::PM_FREQA),
    24, uint(OmniRig::PM_FREQB),
    25, uint(OmniRig::PM_PITCH),
    26, uint(OmniRig::PM_RITOFFSET),
    27, uint(OmniRig::PM_RIT0),
    28, uint(OmniRig::PM_VFOAA),
    29, uint(OmniRig::PM_VFOAB),
    30, uint(OmniRig::PM_VFOBA),
    31, uint(OmniRig::PM_VFOBB),
    32, uint(OmniRig::PM_VFOA),
    33, uint(OmniRig::PM_VFOB),
    34, uint(OmniRig::PM_VFOEQUAL),
    35, uint(OmniRig::PM_VFOSWAP),
    36, uint(OmniRig::PM_SPLITON),
    37, uint(OmniRig::PM_SPLITOFF),
    38, uint(OmniRig::PM_RITON),
    39, uint(OmniRig::PM_RITOFF),
    40, uint(OmniRig::PM_XITON),
    41, uint(OmniRig::PM_XITOFF),
    42, uint(OmniRig::PM_RX),
    43, uint(OmniRig::PM_TX),
    44, uint(OmniRig::PM_CW_U),
    45, uint(OmniRig::PM_CW_L),
    46, uint(OmniRig::PM_SSB_U),
    47, uint(OmniRig::PM_SSB_L),
    48, uint(OmniRig::PM_DIG_U),
    49, uint(OmniRig::PM_DIG_L),
    50, uint(OmniRig::PM_AM),
    51, uint(OmniRig::PM_FM),
    53, uint(OmniRig::ST_NOTCONFIGURED),
    54, uint(OmniRig::ST_DISABLED),
    55, uint(OmniRig::ST_PORTBUSY),
    56, uint(OmniRig::ST_NOTRESPONDING),
    57, uint(OmniRig::ST_ONLINE),
    0 // eod
};

const QMetaObject RigX::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OmniRig__RigX, 0, 0, 0 }
};

void *RigX::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OmniRig::RigX"))
        return static_cast<void*>(const_cast<RigX*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_OmniRig__IPortBits[] = {

 // content:
    7, // revision
    119,  // classname
    0, 0, // classinfo
    7, 14, // methods
    5, 76, // properties
    2, 91, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 49, 2, 5,
    7, 1, 58, 2, 5,
    9, 3, 61, 2, 5,

// slot: name, argc, parameters, tag, flags
    120, 0, 68, 2, 9,
    121, 1, 69, 2, 9,
    123, 1, 72, 2, 9,
    125, 0, 75, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool,
    QMetaType::Void, QMetaType::Bool, 122,
    QMetaType::Void, QMetaType::Bool, 124,
    QMetaType::Void,

 // properties: name, type, flags
    126, QMetaType::Bool, 0x01005001, 		 // bool Cts
    127, QMetaType::Bool, 0x01005001, 		 // bool Dsr
    122, QMetaType::Bool, 0x01015003, 		 // bool Dtr
    124, QMetaType::Bool, 0x01015003, 		 // bool Rts
    19, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    20, 0x0, 31, 99, 
    52, 0x0, 5, 161, 

 // enum data: key, value
    21, uint(OmniRig::PM_UNKNOWN),
    22, uint(OmniRig::PM_FREQ),
    23, uint(OmniRig::PM_FREQA),
    24, uint(OmniRig::PM_FREQB),
    25, uint(OmniRig::PM_PITCH),
    26, uint(OmniRig::PM_RITOFFSET),
    27, uint(OmniRig::PM_RIT0),
    28, uint(OmniRig::PM_VFOAA),
    29, uint(OmniRig::PM_VFOAB),
    30, uint(OmniRig::PM_VFOBA),
    31, uint(OmniRig::PM_VFOBB),
    32, uint(OmniRig::PM_VFOA),
    33, uint(OmniRig::PM_VFOB),
    34, uint(OmniRig::PM_VFOEQUAL),
    35, uint(OmniRig::PM_VFOSWAP),
    36, uint(OmniRig::PM_SPLITON),
    37, uint(OmniRig::PM_SPLITOFF),
    38, uint(OmniRig::PM_RITON),
    39, uint(OmniRig::PM_RITOFF),
    40, uint(OmniRig::PM_XITON),
    41, uint(OmniRig::PM_XITOFF),
    42, uint(OmniRig::PM_RX),
    43, uint(OmniRig::PM_TX),
    44, uint(OmniRig::PM_CW_U),
    45, uint(OmniRig::PM_CW_L),
    46, uint(OmniRig::PM_SSB_U),
    47, uint(OmniRig::PM_SSB_L),
    48, uint(OmniRig::PM_DIG_U),
    49, uint(OmniRig::PM_DIG_L),
    50, uint(OmniRig::PM_AM),
    51, uint(OmniRig::PM_FM),
    53, uint(OmniRig::ST_NOTCONFIGURED),
    54, uint(OmniRig::ST_DISABLED),
    55, uint(OmniRig::ST_PORTBUSY),
    56, uint(OmniRig::ST_NOTRESPONDING),
    57, uint(OmniRig::ST_ONLINE),
    0 // eod
};

const QMetaObject IPortBits::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OmniRig__IPortBits, 0, 0, 0 }
};

void *IPortBits::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OmniRig::IPortBits"))
        return static_cast<void*>(const_cast<IPortBits*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_OmniRig__PortBits[] = {

 // content:
    7, // revision
    128,  // classname
    1, 14, // classinfo
    7, 16, // methods
    4, 78, // properties
    2, 90, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    61, 129, 

// signal: name, argc, parameters, tag, flags
    1, 4, 51, 2, 5,
    7, 1, 60, 2, 5,
    9, 3, 63, 2, 5,

// slot: name, argc, parameters, tag, flags
    120, 0, 70, 2, 9,
    121, 1, 71, 2, 9,
    123, 1, 74, 2, 9,
    125, 0, 77, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool,
    QMetaType::Void, QMetaType::Bool, 122,
    QMetaType::Void, QMetaType::Bool, 124,
    QMetaType::Void,

 // properties: name, type, flags
    126, QMetaType::Bool, 0x01005001, 		 // bool Cts
    127, QMetaType::Bool, 0x01005001, 		 // bool Dsr
    122, QMetaType::Bool, 0x01015003, 		 // bool Dtr
    124, QMetaType::Bool, 0x01015003, 		 // bool Rts

 // enums: name, flags, count, data
    20, 0x0, 31, 98, 
    52, 0x0, 5, 160, 

 // enum data: key, value
    21, uint(OmniRig::PM_UNKNOWN),
    22, uint(OmniRig::PM_FREQ),
    23, uint(OmniRig::PM_FREQA),
    24, uint(OmniRig::PM_FREQB),
    25, uint(OmniRig::PM_PITCH),
    26, uint(OmniRig::PM_RITOFFSET),
    27, uint(OmniRig::PM_RIT0),
    28, uint(OmniRig::PM_VFOAA),
    29, uint(OmniRig::PM_VFOAB),
    30, uint(OmniRig::PM_VFOBA),
    31, uint(OmniRig::PM_VFOBB),
    32, uint(OmniRig::PM_VFOA),
    33, uint(OmniRig::PM_VFOB),
    34, uint(OmniRig::PM_VFOEQUAL),
    35, uint(OmniRig::PM_VFOSWAP),
    36, uint(OmniRig::PM_SPLITON),
    37, uint(OmniRig::PM_SPLITOFF),
    38, uint(OmniRig::PM_RITON),
    39, uint(OmniRig::PM_RITOFF),
    40, uint(OmniRig::PM_XITON),
    41, uint(OmniRig::PM_XITOFF),
    42, uint(OmniRig::PM_RX),
    43, uint(OmniRig::PM_TX),
    44, uint(OmniRig::PM_CW_U),
    45, uint(OmniRig::PM_CW_L),
    46, uint(OmniRig::PM_SSB_U),
    47, uint(OmniRig::PM_SSB_L),
    48, uint(OmniRig::PM_DIG_U),
    49, uint(OmniRig::PM_DIG_L),
    50, uint(OmniRig::PM_AM),
    51, uint(OmniRig::PM_FM),
    53, uint(OmniRig::ST_NOTCONFIGURED),
    54, uint(OmniRig::ST_DISABLED),
    55, uint(OmniRig::ST_PORTBUSY),
    56, uint(OmniRig::ST_NOTRESPONDING),
    57, uint(OmniRig::ST_ONLINE),
    0 // eod
};

const QMetaObject PortBits::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OmniRig__PortBits, 0, 0, 0 }
};

void *PortBits::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OmniRig::PortBits"))
        return static_cast<void*>(const_cast<PortBits*>(this));
    return QAxObject::qt_metacast(_clname);
}
#endif
#endif
