name: Build for Windows 10+ amd64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_windows-2022:
    runs-on: windows-2025

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git python base-devel make
        pacboy: >-
          toolchain:p
          autotools:p
          cmake:p
          ninja:p
          libusb:p
          wget:p
          boost:p
          fftw:p
          qt6:p
          sqlite3:p
          nsis:p
          pkgconfig:p
          
    - shell: msys2 {0}
      run: |
        uname -a
      
    - shell: msys2 {0}
      name: Build Hamlib
      run: |
        git clone https://github.com/Hamlib/Hamlib.git ~/development/hamlib
        cd ~/development/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        make install-strip

    - name: Setup build directories
      shell: msys2 {0}
      run: |
        mkdir ~/development && mkdir ~/development/js8libs
        cd ~/development
        git clone https://github.com/js8call/js8call.git ~/development/js8call
        mkdir -p ~/development/js8call/build && cd ~/development/js8call/build
     
    - name: Install OmniRig
      shell: msys2 {0}
      run: |
        cd ~/development
        wget http://dxatlas.com/OmniRig/Files/OmniRig.zip
        unzip OmniRig.zip
        cd ~/development/OmniRig
        powershell.exe -Command -ScriptBlock { cmd /c OmniRigSetup.exe *> $null;}

    - name: Build JS8Call 
      shell: msys2 {0}
      run: |
        cd ~/development/js8call/build
        cmake ..
        make -j 4

    - name: Upload Artifact (app)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_amd64_win64.exe
        path: ~/development/js8call/build/js8call.exe
        retention-days: 7
