name: Build for MacOS 15

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_macos-latest:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Get CMake and build
      run: |
        cd ~
        wget -q https://github.com/Kitware/CMake/releases/download/v4.0.3/cmake-4.0.3.tar.gz
        tar zxf cmake-4.0.3.tar.gz
        ls -l
        
#    - name: Install dependencies
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y build-essential git cmake libhamlib-dev qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
#          libusb-1.0-0-dev libfftw3-dev libboost-all-dev libudev-dev libxkbcommon-dev libfuse2 imagemagick

#    - name: Build Hamlib
#      run: |
#        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
#        cd ~/hamlib
#        git checkout 4.6.4
#        ./bootstrap
#        ./configure
#        make -j 4
#        sudo make install-strip
#        sudo ldconfig

#    - name: Build JS8Call 
#      run: |
#        git clone https://github.com/js8call/js8call.git ~/js8call
#        mkdir -p ~/js8call/build && cd ~/js8call/build
#        cmake ..
#        make -j 4

#    - name: Package JS8Call (deb)
#      run: |
#        cd ~/js8call/build
#        cpack -G DEB

#    - name: Upload Artifact (deb)
#      uses: actions/upload-artifact@v4
#      with:
#        name: js8call_2.3.2-devel_amd64_ubuntu-24.04.deb
#        path: ~/js8call/build/js8call_2.3.2-devel_amd64.deb
#        retention-days: 7
