permissions:
  contents: read

name: Build for MacOS 15 Arm64 (M1 and higher)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_macos-latest:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    
#    - name: Install CMake
#      run: |
#        brew update
#        brew install cmake
        
#    - name: Install Ninja
#      run: brew install ninja

#    - name: Install libusb
#      run: brew install libusb

#    - name: Install Hamlib
#      run: brew install hamlib

#    - name: Install Boost
#      run: brew install boost
        
    - name: Download dependencies
      run: |
        mkdir ~/development && mkdir ~/development/js8libs
        cd ~/development
        wget -q https://fftw.org/fftw-3.3.10.tar.gz
        tar zxf fftw-3.3.10.tar.gz
        wget -q https://github.com/Chris-AC9KH/js8lib/releases/download/js8lib-2.3/js8lib-2.3_Darwin_arm64.tar.gz
#        git clone https://github.com/qt/qt5.git qt6
#        cd qt6
#        git switch 6.6.3
#        ./init-repository

    - name: Install AC9KH package
      run: |
        tar zxf js8lib-2.3_Darwin_arm64.tar.gz
        ls
        
    - name: Build and install fftw
      run: |
       cd ~/development/fftw-3.3.10 \
            && ./configure CFLAGS=-mmacosx-version-min=11.0 \
                    --prefix=/Users/runner/development/js8libs \
                    --enable-single \
                    --enable-threads \
                    --enable-neon
        make \
        && make install \
        && make clean

    - name: Build and install QT6
      run: |
       mkdir ~/development/qt6-build && cd ~/development/qt6-build \
            && ../qt6/configure -prefix ~/development/js8libs \
            && cmake --build . --parallel \
            && cmake --install .
        
    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/development/js8call
        mkdir -p ~/development/js8call/build && cd ~/development/js8call/build
        cmake -DCMAKE_PREFIX_PATH="/Users/runner/development/js8libs" ..
        make
        make install

    - name: Upload Artifact (app)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_arm64_macos15.app
        path: ~/development/js8call/build/js8call.app
