permissions:
  contents: read

name: Build for Debian x86_64 and Arm64

on:
  push:
    branches: [ "main" ]
    paths:
      '.github/workflows/build-ubuntu.yml'
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_amd64_2404:
    permissions: write-all
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake libhamlib-dev qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libboost-all-dev libudev-dev libxkbcommon-dev libfuse2 imagemagick

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        sudo make install-strip
        sudo ldconfig

    - name: Build JS8Call 
      run: |
        pwd
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        pwd
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_amd64_ubuntu-24.04.deb
        path: ~/js8call/build/js8call_2.3.2-devel_amd64.deb

    - name: Package JS8Call AppImage (amd64)
      run: |
        mkdir -p ~/appimage/AppDir
        cd ~/js8call/build
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
          && wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage \
          && chmod +x linuxdeploy*.AppImage \
          && ./linuxdeploy-x86_64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy \
          && ./linuxdeploy-plugin-qt-x86_64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy-plugin-qt \
          && rm *.AppImage

        make DESTDIR=~/appimage/AppDir install
        
        test -f ~/appimage/AppDir/usr/share/applications/js8call.desktop || \
          cp ~/js8call/js8call.desktop ~/appimage/AppDir/usr/share/applications/ && \
        if [ ! -f ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png ]; then \
        mkdir -p ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps && \
        convert ~/js8call/artwork/js8call_icon.png -resize 128x128 \
            ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png; \
        fi
        cd ~/appimage

        echo "~/js8call/build/linuxdeploy/usr/bin:~/js8call/build/linuxdeploy-plugin-qt/usr/bin/" >> "$GITHUB_PATH"
        ln -s ~/js8call/build/linuxdeploy-plugin-qt/usr/bin/linuxdeploy-plugin-qt ~/js8call/build/linuxdeploy/usr/bin/
        
        EXEC_PATH=$(find AppDir -type f -name "js8call" -executable | head -1) && \
          echo "Found executable at: $EXEC_PATH" && \
          ~/js8call/build/linuxdeploy/usr/bin/linuxdeploy --appdir AppDir \
          --executable "$EXEC_PATH" \
          --plugin qt \
          --output appimage \
          --desktop-file AppDir/usr/share/applications/js8call.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_ubuntu-24.04.AppImage
        path: ~/appimage/js8call-x86_64.AppImage

    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Create zip file to upload to release page (ubuntu-24.04-amd64)
      run: |
        cd ~/appimage/
        tar zcf /home/runner/work/js8call/js8call/js8call_2.3.2-devel_24.04-amd64-ci.tar.gz js8call-x86_64.AppImage
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call_2.3.2-devel_ubuntu-24.04-amd64-ci
        name: "JS8Call v2.3.2-devel Ubuntu 24.04 amd64 CI AppImage build"
        body: |
          Release created automatically from commit ${{ steps.get_sha.outputs.short_sha }}.
          This AppImage release is from the Ubuntu 24.04 amd64 CI build for JS8Call. Use at your own risk!
        files: /home/runner/work/js8call/js8call/js8call_2.3.2-devel_24.04-amd64-ci.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  
  build_arm64_2404:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake libhamlib-dev qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libboost-all-dev libudev-dev libxkbcommon-dev libfuse2 imagemagick

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        sudo make install-strip
        sudo ldconfig

    - name: Build JS8Call
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_arm64_ubuntu-24.04.deb
        path: ~/js8call/build/js8call_2.3.2-devel_arm64.deb
        
    - name: Package JS8Call AppImage (arm64)
      run: |
        mkdir -p ~/appimage/AppDir
        cd ~/js8call/build
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage \
          && wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-aarch64.AppImage \
          && chmod +x linuxdeploy*.AppImage \
          && ./linuxdeploy-aarch64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy \
          && ./linuxdeploy-plugin-qt-aarch64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy-plugin-qt \
          && rm *.AppImage

        make DESTDIR=~/appimage/AppDir install
        
        test -f ~/appimage/AppDir/usr/share/applications/js8call.desktop || \
          cp ~/js8call/js8call.desktop ~/appimage/AppDir/usr/share/applications/ && \
        if [ ! -f ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png ]; then \
        mkdir -p ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps && \
        convert ~/js8call/artwork/js8call_icon.png -resize 128x128 \
            ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png; \
        fi
        cd ~/appimage

        echo "~/js8call/build/linuxdeploy/usr/bin:~/js8call/build/linuxdeploy-plugin-qt/usr/bin/" >> "$GITHUB_PATH"
        ln -s ~/js8call/build/linuxdeploy-plugin-qt/usr/bin/linuxdeploy-plugin-qt ~/js8call/build/linuxdeploy/usr/bin/
        
        EXEC_PATH=$(find AppDir -type f -name "js8call" -executable | head -1) && \
          echo "Found executable at: $EXEC_PATH" && \
          ~/js8call/build/linuxdeploy/usr/bin/linuxdeploy --appdir AppDir \
          --executable "$EXEC_PATH" \
          --plugin qt \
          --output appimage \
          --desktop-file AppDir/usr/share/applications/js8call.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_ubuntu-24.04.AppImage
        path: ~/appimage/js8call-aarch64.AppImage
        
    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
        
    - name: Create zip file to upload to release page (ubuntu-24.04-aarch64)
      run: |
        cd ~/appimage/
        tar zcf /home/runner/work/js8call/js8call/js8call_2.3.2-devel_24.04-aarch64-ci.tar.gz js8call-aarch64.AppImage
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call_2.3.2-devel_ubuntu-24.04-aarch64-ci
        name: "JS8Call v2.3.2-devel Ubuntu 24.04 aarch64/arm64 CI AppImage build"
        body: |
          Release created automatically from commit ${{ steps.get_sha.outputs.short_sha }}.
          This AppImage release is from the Ubuntu 24.04 aarch64/arm64 CI build for JS8Call. Use at your own risk!
        files: /home/runner/work/js8call/js8call/js8call_2.3.2-devel_24.04-aarch64-ci.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build_x86_64_Debian12:
    runs-on: ubuntu-latest
    permissions: write-all
    
    container:
      image: debian:bookworm
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        apt-get update
        apt-get install -y build-essential git cmake curl wget automake libtool libfuse2 imagemagick \
          qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libudev-dev libxkbcommon-dev \
          libhamlib-dev

    - name: Install Boost 1.88
      id: install-boost
      run: |
        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
        tar zxf boost-1.88.0.tar.gz
        cd boost_1_88_0
        ./bootstrap.sh
        ./b2 install

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        make install-strip
        ldconfig

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_debian-12.deb
        path: ~/js8call/build/js8call_2.3.2-devel_amd64.deb

    - name: Package JS8Call Debian 12 AppImage (x86_64)
      run: |
        mkdir -p ~/appimage/AppDir
        cd ~/js8call/build
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
          && wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage \
          && chmod +x linuxdeploy*.AppImage \
          && ./linuxdeploy-x86_64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy \
          && ./linuxdeploy-plugin-qt-x86_64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy-plugin-qt \
          && rm *.AppImage

        make DESTDIR=~/appimage/AppDir install
        
        test -f ~/appimage/AppDir/usr/share/applications/js8call.desktop || \
          cp ~/js8call/js8call.desktop ~/appimage/AppDir/usr/share/applications/ && \
        if [ ! -f ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png ]; then \
        mkdir -p ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps && \
        convert ~/js8call/artwork/js8call_icon.png -resize 128x128 \
            ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png; \
        fi
        cd ~/appimage

        echo "~/js8call/build/linuxdeploy/usr/bin:~/js8call/build/linuxdeploy-plugin-qt/usr/bin/" >> "$GITHUB_PATH"
        ln -s ~/js8call/build/linuxdeploy-plugin-qt/usr/bin/linuxdeploy-plugin-qt ~/js8call/build/linuxdeploy/usr/bin/
        
        EXEC_PATH=$(find AppDir -type f -name "js8call" -executable | head -1) && \
          echo "Found executable at: $EXEC_PATH" && \
          ~/js8call/build/linuxdeploy/usr/bin/linuxdeploy --appdir AppDir \
          --executable "$EXEC_PATH" \
          --plugin qt \
          --output appimage \
          --desktop-file AppDir/usr/share/applications/js8call.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_debian-12.AppImage
        path: ~/appimage/js8call-x86_64.AppImage
        
    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
        
    - name: Create zip file to upload to release page (debian-12-x86_64)
      run: |
        cd ~/appimage/
        tar zcf /__w/js8call/js8call/js8call_2.3.2-devel_deb12-x86_64-ci.tar.gz js8call-x86_64.AppImage
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call_2.3.2-devel_debian-12-x86_64-ci
        name: "JS8Call v2.3.2-devel Debian 12 x86_64 CI AppImage build"
        body: |
          Release created automatically from commit ${{ steps.get_sha.outputs.short_sha }}.
          This AppImage release is from the Debian 12 x86_64 CI build for JS8Call. Use at your own risk!
        files: /__w/js8call/js8call/js8call_2.3.2-devel_deb12-x86_64-ci.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_arm64_Debian12:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    
    container:
      image: arm64v8/debian:bookworm
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        apt-get update
        apt-get install -y build-essential git cmake curl wget automake libtool libfuse2 imagemagick \
          qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libudev-dev libxkbcommon-dev \
          libhamlib-dev

    - name: Install Boost 1.88
      id: install-boost
      run: |
        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
        tar zxf boost-1.88.0.tar.gz
        cd boost_1_88_0
        ./bootstrap.sh
        ./b2 install

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        make install-strip
        ldconfig

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_debian-12.deb
        path: ~/js8call/build/js8call_2.3.2-devel_arm64.deb
        
    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Package JS8Call Debian 12 AppImage (arm64)
      run: |
        mkdir -p ~/appimage/AppDir
        cd ~/js8call/build
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage \
          && wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-aarch64.AppImage \
          && chmod +x linuxdeploy*.AppImage \
          && ./linuxdeploy-aarch64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy \
          && ./linuxdeploy-plugin-qt-aarch64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy-plugin-qt \
          && rm *.AppImage

        make DESTDIR=~/appimage/AppDir install
        
        test -f ~/appimage/AppDir/usr/share/applications/js8call.desktop || \
          cp ~/js8call/js8call.desktop ~/appimage/AppDir/usr/share/applications/ && \
        if [ ! -f ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png ]; then \
        mkdir -p ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps && \
        convert ~/js8call/artwork/js8call_icon.png -resize 128x128 \
            ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png; \
        fi
        cd ~/appimage

        echo "~/js8call/build/linuxdeploy/usr/bin:~/js8call/build/linuxdeploy-plugin-qt/usr/bin/" >> "$GITHUB_PATH"
        ln -s ~/js8call/build/linuxdeploy-plugin-qt/usr/bin/linuxdeploy-plugin-qt ~/js8call/build/linuxdeploy/usr/bin/
        
        EXEC_PATH=$(find AppDir -type f -name "js8call" -executable | head -1) && \
          echo "Found executable at: $EXEC_PATH" && \
          ~/js8call/build/linuxdeploy/usr/bin/linuxdeploy --appdir AppDir \
          --executable "$EXEC_PATH" \
          --plugin qt \
          --output appimage \
          --desktop-file AppDir/usr/share/applications/js8call.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_debian-12.AppImage
        path: ~/appimage/js8call-aarch64.AppImage

    - name: Create zip file to upload to release page (debian-12-aarch64)
      run: |
        cd ~/appimage/
        tar zcf /__w/js8call/js8call/js8call_2.3.2-devel_debian-12-aarch64-ci.tar.gz js8call-aarch64.AppImage
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call_2.3.2-devel_debian-12-aarch64-ci
        name: "JS8Call v2.3.2-devel Debian 12 aarch64/arm64 CI AppImage build"
        body: |
          Release created automatically from commit ${{ steps.get_sha.outputs.short_sha }}.
          This AppImage release is from the Debian 12 aarch64/arm64 CI build for JS8Call. Use at your own risk!
        files: /__w/js8call/js8call/js8call_2.3.2-devel_debian-12-aarch64-ci.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Fedora builds
  build_x86_64_Fedora42:
    runs-on: ubuntu-latest
    permissions: write-all
    
    container:
      image: amd64/fedora:42
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        dnf upgrade -y --refresh
        dnf install -y gcc git clang which fuse ImageMagick cmake curl wget automake libtool \
          qt6-qtbase-devel qt6-qtmultimedia-devel qt6-qtserialport-devel libudev-devel \
          libusb1-devel fftw-devel libxkbcommon-devel hamlib-devel rpm-build boost-devel

# Use Boost 1.83 from package repo
#    - name: Install Boost 1.88
#      id: install-boost
#      run: |
#        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
#        tar zxf boost-1.88.0.tar.gz
#        cd boost_1_88_0
#        ./bootstrap.sh
#        ./b2 install

# Use Hamlib 4.6.4 from package repo
#    - name: Build Hamlib
#      run: |
#        ldd --version
#        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
#        cd ~/hamlib
#        git checkout 4.6.4
#        ./bootstrap
#        ./configure
#        make -j 4
#        make install-strip
#        ldconfig

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake -D CMAKE_INSTALL_PREFIX=/opt/js8call ..
        cmake --build . -- -j 4

# Below 2 aren't working atm
# Failing on the rigctl/d runpaths
    - name: Package JS8Call (rpm)
      run: |
        cd ~/js8call/build
        cpack -G RPM
      continue-on-error: true

    - name: Upload Artifact (rpm)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_fedora-42.rpm
        path: ~/js8call/build/js8call-2.3.2-devel.x86_64.rpm
      continue-on-error: true
      
    - name: Package JS8Call Fedora 42 AppImage (x86_64)
      run: |
        mkdir -p ~/appimage/AppDir
        cd ~/js8call/build
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
          && wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage \
          && chmod +x linuxdeploy*.AppImage \
          && ./linuxdeploy-x86_64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy \
          && ./linuxdeploy-plugin-qt-x86_64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy-plugin-qt \
          && rm *.AppImage

        make DESTDIR=~/appimage/AppDir install
        
        test -f ~/appimage/AppDir/usr/share/applications/js8call.desktop || \
          cp ~/js8call/js8call.desktop ~/appimage/AppDir/usr/share/applications/ && \
        if [ ! -f ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png ]; then \
        mkdir -p ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps && \
        magick ~/js8call/artwork/js8call_icon.png -resize 128x128 \
            ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png; \
        fi
        cd ~/appimage

        echo "~/js8call/build/linuxdeploy/usr/bin:~/js8call/build/linuxdeploy-plugin-qt/usr/bin/" >> "$GITHUB_PATH"
        ln -s ~/js8call/build/linuxdeploy-plugin-qt/usr/bin/linuxdeploy-plugin-qt ~/js8call/build/linuxdeploy/usr/bin/

        ls -l $(find AppDir -type f -name "js8call" -executable | head -1)
        
        EXEC_PATH=$(find AppDir -type f -name "js8call" -executable | head -1) && \
          echo "Found executable at: $EXEC_PATH" && \
          ~/js8call/build/linuxdeploy/usr/bin/linuxdeploy --appdir AppDir \
          --executable "$EXEC_PATH" \
          --plugin qt \
          --output appimage \
          --desktop-file AppDir/usr/share/applications/js8call.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png
      continue-on-error: true
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_fedora-42.AppImage
        path: ~/appimage/js8call-x86_64.AppImage
      continue-on-error: true
        
    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
        
    - name: Create zip file to upload to release page (fedora-42-x86_64)
      run: |
        cd ~/appimage/
        tar zcf /__w/js8call/js8call/js8call_2.3.2-devel_fed42-x86_64-ci.tar.gz js8call-x86_64.AppImage
      continue-on-error: true
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call_2.3.2-devel_fedora-42-x86_64-ci
        name: "JS8Call v2.3.2-devel Fedora 42 x86_64 CI AppImage build"
        body: |
          Release created automatically from commit ${{ steps.get_sha.outputs.short_sha }}.
          This AppImage release is from the Fedora 42 x86_64 CI build for JS8Call. Use at your own risk!
        files: /__w/js8call/js8call/js8call_2.3.2-devel_fed42-x86_64-ci.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_arm64_Fedora42:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    
    container:
      image: arm64v8/fedora:42
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        dnf upgrade -y --refresh
        dnf install -y gcc git clang which fuse ImageMagick cmake curl wget automake libtool \
          qt6-qtbase-devel qt6-qtmultimedia-devel qt6-qtserialport-devel \
          libusb1-devel fftw-devel libxkbcommon-devel hamlib-devel rpm-build libudev-devel boost-devel

# Use Boost 1.83 from package repo
#    - name: Install Boost 1.88
#      id: install-boost
#      run: |
#        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
#        tar zxf boost-1.88.0.tar.gz
#        cd boost_1_88_0
#        ./bootstrap.sh
#        ./b2 install

# Use Hamlib 4.6.4 from package repo
#    - name: Build Hamlib
#      run: |
#        ldd --version
#        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
#        cd ~/hamlib
#        git checkout 4.6.4
#        ./bootstrap
#        ./configure
#        make -j 4
#        make install-strip
#        ldconfig

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake -D CMAKE_INSTALL_PREFIX=/opt/js8call ..
        cmake --build . -- -j 4

# Below 2 aren't working atm
# Failing on the rigctl/d runpaths
    - name: Package JS8Call (rpm)
      run: |
        cd ~/js8call/build
        cpack -G RPM
      continue-on-error: true
      
    - name: Upload Artifact (fed)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_fedora-42.rpm
        path: ~/js8call/build/js8call-2.3.2-devel_arm64.rpm
      continue-on-error: true
      
    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Package JS8Call Fedora 42 AppImage (arm64)
      run: |
        mkdir -p ~/appimage/AppDir
        cd ~/js8call/build
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage \
          && wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-aarch64.AppImage \
          && chmod +x linuxdeploy*.AppImage \
          && ./linuxdeploy-aarch64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy \
          && ./linuxdeploy-plugin-qt-aarch64.AppImage --appimage-extract \
          && mv squashfs-root linuxdeploy-plugin-qt \
          && rm *.AppImage

        make DESTDIR=~/appimage/AppDir install
        
        test -f ~/appimage/AppDir/usr/share/applications/js8call.desktop || \
          cp ~/js8call/js8call.desktop ~/appimage/AppDir/usr/share/applications/ && \
        if [ ! -f ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png ]; then \
        mkdir -p ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps && \
        magick ~/js8call/artwork/js8call_icon.png -resize 128x128 \
            ~/appimage/AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png; \
        fi
        cd ~/appimage

        echo "~/js8call/build/linuxdeploy/usr/bin:~/js8call/build/linuxdeploy-plugin-qt/usr/bin/" >> "$GITHUB_PATH"
        ln -s ~/js8call/build/linuxdeploy-plugin-qt/usr/bin/linuxdeploy-plugin-qt ~/js8call/build/linuxdeploy/usr/bin/

        ls -l $(find AppDir -type f -name "js8call" -executable | head -1)
        
        EXEC_PATH=$(find AppDir -type f -name "js8call" -executable | head -1) && \
          echo "Found executable at: $EXEC_PATH" && \
          ~/js8call/build/linuxdeploy/usr/bin/linuxdeploy --appdir AppDir \
          --executable "$EXEC_PATH" \
          --plugin qt \
          --output appimage \
          --desktop-file AppDir/usr/share/applications/js8call.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/js8call_icon.png
      continue-on-error: true
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_fedora-12.AppImage
        path: ~/appimage/js8call-aarch64.AppImage
      continue-on-error: true

    - name: Create zip file to upload to release page (fedora-42-aarch64)
      run: |
        cd ~/appimage/
        tar zcf /__w/js8call/js8call/js8call_2.3.2-devel_fedora-42-aarch64-ci.tar.gz js8call-aarch64.AppImage
      continue-on-error: true
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call_2.3.2-devel_fedora-42-aarch64-ci
        name: "JS8Call v2.3.2-devel Fedora 42 aarch64/arm64 CI AppImage build"
        body: |
          Release created automatically from commit ${{ steps.get_sha.outputs.short_sha }}.
          This AppImage release is from the Fedora 42 aarch64/arm64 CI build for JS8Call. Use at your own risk!
        files: /__w/js8call/js8call/js8call_2.3.2-devel_fedora-42-aarch64-ci.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
