name: Build for MacOS 15 Arm64 (M1 and higher)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_macos-latest:
    runs-on: macos-15
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Work around for /usr/local perms and grab arch/os info
      run: |
        sudo chown runner:admin /usr/local
      
    - name: Download and Install Release AC9KH package
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'Chris-AC9KH/js8lib'
        fileName: 'js8lib-2.3_Darwin_arm64_Qt6.6.3.tar.gz'
        latest: true
        extract: true
        out-file-path: '/usr/local/'

    - name: Look for and delete files that break app building
      run: |
        find /usr/local/js8lib -type f -name ._* -delete
      continue-on-error: true

    - name: Build JS8Call and tar.gz the app
      run: |
        mkdir -p ./build && cd ./build
        cmake -DCMAKE_PREFIX_PATH="/usr/local/js8lib" ..
        make
        make install
        tar zcf ../js8call_2.3.2-devel_arm64_macos15.app.tar.gz js8call.app

    - name: Upload Artifact (app)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_arm64_macos15.app
        path: /Users/runner/work/js8call/js8call/js8call_2.3.2-devel_arm64_macos15.app.tar.gz
