name: Build for Windows 10+ amd64

on:
  push:
    branches: [ "main" ]
    paths:
      '.github/workflows/build-win64.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      '.github/workflows/build-win64.yml'
      
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_windows-2022:
    runs-on: self-hosted
    permissions: write-all

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git python base-devel make unzip zip tar
        pacboy: >-
          toolchain:p
          autotools:p
          cmake:p
          ninja:p
          libusb:p
          wget:p
          boost:p
          fftw:p
          sqlite3:p
          nsis:p

    - name: Setup build directories
      shell: msys2 {0}
      run: |
        pwd
        mkdir -p js8libs
        mkdir -p build
        
# NOTE: So long as these are coming from a branch, the run-id and artifact-ids have to be kept updated.
#    - name: Download qt663-windows-msys2-binaries
#      uses: actions/download-artifact@v5
#      with:
#        repository: wmiler/js8call
#        run-id: 17137490514
#        artifact-ids: 3823059396
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        path: "C:/actions-runner/_work/_temp/msys64/mingw64/"

    - name: Release download for QT6
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'wmiler/js8call'
        fileName: 'qt663-windows-msys2-binaries*.zip'
        tag: 'qt6-v6.6.3-ci'
        extract: true
        out-file-path: 'C:/actions-runner/_work/_temp/msys64/mingw64/'

    - name: Release download for hamlib
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'wmiler/js8call'
        fileName: 'hamlib-windows-msys2-binaries*.zip'
        tag: 'hamlib-v4.6.4-ci'
        extract: true
        out-file-path: 'C:/actions-runner/_work/_temp/msys64/mingw64/'
       
    - name: Install OmniRig
      run: |
        winget install --id=AfreetSoftware.OmniRig --exact --silent --disable-interactivity --accept-package-agreements --accept-source-agreements
                
    - name: Configure JS8Call
      shell: msys2 {0}
      run: |
        pwd
        cd ./build
        cmake -DCMAKE_FIND_DEBUG_MODE=1 -G "MinGW Makefiles" ..

    - name: Build JS8Call
      shell: msys2 {0}
      run: |
        pwd
        cd ./build
        cmake --build . --config Release --target package

    - name: Upload Artifact (from self-hosted)
      uses: actions/upload-artifact@v4
      with:
        name: js8call-2.3.2-devel-win64.exe
        path: "C:/actions-runner/_work/js8call/js8call/build/js8call-2.3.2-devel-win64.exe"

# This doesn't work if we keep commiting to the same tag
#    - name: Create GitHub Release and get short commit SHA
#      id: get_sha
#      run: |
#        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
#
#    - name: Create Git Tag
#      id: create_tag
#      uses: actions/github-script@v7
#      with:
#        script: |
#          const shortSha = process.env.SHORT_SHA;
#          const tagName = `js8call-v2.3.2-devel-ci`;
#            
#          await github.rest.git.createRef({
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            ref: `refs/tags/${tagName}`,
#            sha: context.sha,
#          });
#          console.log(`Tag '${tagName}' created.`);
#      env:
#        SHORT_SHA: ${{ steps.get_sha.outputs.short_sha }}
#      continue-on-error: true

    - name: Create zip file to upload to release page
      shell: msys2 {0}
      run: |
        pwd
        zip -r "C:/actions-runner/_work/js8call/js8call/js8call-2.3.2-devel-win64.exe-ci.zip" "C:/actions-runner/_work/js8call/js8call/build/js8call-2.3.2-devel-win64.exe"
      continue-on-error: true

    - name: Create zip file to upload to release page from powershell
      shell: pwsh
      run: |
         Compress-Archive -Path "C:/actions-runner/_work/js8call/js8call/build/js8call-2.3.2-devel-win64.exe" -DestinationPath "C:/actions-runner/_work/js8call/js8call/js8call-2.3.2-devel-win64.exe-pswh-ci.zip"
      continue-on-error: true

         
    - name: Create Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        mode: "COMMIT"
        configurationJson: |
          {
            "template": "#{{CHANGELOG}}",
            "categories": [
              {
                  "title": "## Feature",
                  "labels": ["feat", "feature"]
              },
              {
                  "title": "## Fix",
                  "labels": ["fix", "bug"]
              },
              {
                  "title": "## Other",
                  "labels": []
              }
            ],
            "label_extractor": [
              {
                "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                "on_property": "title",
                "target": "$1"
              }
            ]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: js8call-v2.3.2-devel-ci
        name: "JS8Call v2.3.2-devel Windows MSYS2 CI build ${{ steps.get_sha.outputs.short_sha }}"
        prerelease: true
        body: |
          Release created automatically from commit ${{ github.sha }}.
          This release is for use in the Windows MSYS2 CI builds for JS8Call. Use at your own risk!
          ${{steps.github_release.outputs.changelog}}
        files: js8call-2.3.2-devel-win64.exe*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
