permissions:
  contents: read

name: Build for Debian x86_64 and Arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_amd64_2404:
    permissions: write-all
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake libhamlib-dev qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libboost-all-dev libudev-dev libxkbcommon-dev libfuse2 imagemagick

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        sudo make install-strip
        sudo ldconfig

    - name: Build JS8Call 
      run: |
        pwd
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        pwd
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_amd64_ubuntu-24.04.deb
        path: ~/js8call/build/js8call_2.3.2-devel_amd64.deb
                  
  build_arm64_2404:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake libhamlib-dev qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libboost-all-dev libudev-dev libxkbcommon-dev libfuse2 imagemagick

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        sudo make install-strip
        sudo ldconfig

    - name: Build JS8Call
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_arm64_ubuntu-24.04.deb
        path: ~/js8call/build/js8call_2.3.2-devel_arm64.deb
 
  build_x86_64_Debian12:
    runs-on: ubuntu-latest
    permissions: write-all
    
    container:
      image: debian:bookworm
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        apt-get update
        apt-get install -y build-essential git cmake curl wget automake libtool libfuse2 imagemagick \
          qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libudev-dev libxkbcommon-dev \
          libhamlib-dev

    - name: Install Boost 1.88
      id: install-boost
      run: |
        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
        tar zxf boost-1.88.0.tar.gz
        cd boost_1_88_0
        ./bootstrap.sh
        ./b2 install

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        make install-strip
        ldconfig

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_debian-12.deb
        path: ~/js8call/build/js8call_2.3.2-devel_amd64.deb

  build_arm64_Debian12:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    
    container:
      image: arm64v8/debian:bookworm
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        apt-get update
        apt-get install -y build-essential git cmake curl wget automake libtool libfuse2 imagemagick \
          qt6-base-dev qt6-multimedia-dev qt6-serialport-dev \
          libusb-1.0-0-dev libfftw3-dev libudev-dev libxkbcommon-dev \
          libhamlib-dev

    - name: Install Boost 1.88
      id: install-boost
      run: |
        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
        tar zxf boost-1.88.0.tar.gz
        cd boost_1_88_0
        ./bootstrap.sh
        ./b2 install

    - name: Build Hamlib
      run: |
        ldd --version
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure
        make -j 4
        make install-strip
        ldconfig

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake ..
        make -j 4

    - name: Package JS8Call (deb)
      run: |
        cd ~/js8call/build
        cpack -G DEB

    - name: Upload Artifact (deb)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_debian-12.deb
        path: ~/js8call/build/js8call_2.3.2-devel_arm64.deb
        
# Fedora builds
  build_x86_64_Fedora42:
    runs-on: ubuntu-latest
    permissions: write-all
    
    container:
      image: amd64/fedora:42
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        dnf upgrade -y --refresh
        dnf install -y gcc git clang which fuse ImageMagick cmake curl wget automake libtool \
          qt6-qtbase-devel qt6-qtmultimedia-devel qt6-qtserialport-devel libudev-devel \
          libusb1-devel fftw-devel libxkbcommon-devel hamlib-devel rpm-build boost-devel

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake -D CMAKE_INSTALL_PREFIX=/opt/js8call ..
        cmake --build . -- -j 4

    - name: Package JS8Call (rpm)
      run: |
        cd ~/js8call/build
        cpack -G RPM

    - name: Upload Artifact (rpm)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_x86_64_fedora-42.rpm
        path: ~/js8call/build/js8call-2.3.2-devel.x86_64.rpm

  build_arm64_Fedora42:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    
    container:
      image: arm64v8/fedora:42
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        uname -a
        dnf upgrade -y --refresh
        dnf install -y gcc git clang which fuse ImageMagick cmake curl wget automake libtool \
          qt6-qtbase-devel qt6-qtmultimedia-devel qt6-qtserialport-devel \
          libusb1-devel fftw-devel libxkbcommon-devel hamlib-devel rpm-build libudev-devel boost-devel

    - name: Build JS8Call 
      run: |
        git clone https://github.com/js8call/js8call.git ~/js8call
        mkdir -p ~/js8call/build && cd ~/js8call/build
        cmake -D CMAKE_INSTALL_PREFIX=/opt/js8call ..
        cmake --build . -- -j 4

    - name: Package JS8Call (rpm)
      run: |
        cd ~/js8call/build
        cpack -G RPM
      
    - name: Upload Artifact (arm64 fed)
      uses: actions/upload-artifact@v4
      with:
        name: js8call_2.3.2-devel_aarch64_fedora-42.rpm
        path: ~/js8call/build/js8call-2.3.2-devel.aarch64.rpm
