name: Build fftw on Windows (MSYS2)

on:
  push:
    paths:
      '.github/workflows/fftw-msys.yml'

jobs:
  build-hamlib-windows-msys2:
    runs-on: windows-2025
    permissions: write-all
  
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
            zip
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

      - name: Fetch and setup fftw
        run: |
          cd /tmp
          curl --location --output /tmp/fftw-3.3.10.tar.gz https://www.fftw.org/fftw-3.3.10.tar.gz
          tar zxf fftw-3.3.10.tar.gz

      - name: Configure and make fftw
        if: (runner.arch == 'X64')
        run: |
          cd /tmp/fftw-3.3.10
          ./configure --prefix=${GITHUB_WORKSPACE}/local/fftw --enable-threads --enable-shared --enable-sse2 --enable-avx --enable-avx2 --enable-float --with-our-malloc
          make
          make install
          
      - name: ls fftw
        run: ls -l ${GITHUB_WORKSPACE}/local/fftw

      - name: Upload fftw binaries
        uses: actions/upload-artifact@v5
        with:
          name: fftw-windows-msys2-binaries
          path: "D:/a/js8call/fftw-install/"

      - name: Create zip file to upload to release page
        run: |
          pwd
          cd ../fftw-install/
          zip -r /d/a/js8call/js8call/fftw-windows-msys2-binaries-ci.zip .

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2.4.2
        with:
          tag_name: fftw-v3.3.10-ci
          name: "fftw v3.3.10 for Windows MSYS2 CI build"
          body: |
            Release created automatically from commit.
            This release is for use in the Windows MSYS2 CI builds for JS8Call. Use at your own risk!
          files: fftw-windows-msys2-binaries-ci.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
