name: Build Hamlib SDK on Windows (MSYS2)

on:
  push:
    branches:
      - build-artifacts
    paths:
      '.github/workflows/hamlib-msys.yml'

jobs:
  build-hamlib-windows-msys2:
    runs-on: windows-2025
    permissions:
      contents: write

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'Hamlib/Hamlib.git'
          ref: '4.6.4' 
          fetch-depth: 0 
          persist-credentials: false
          submodules: recursive
          lfs: true
          clean: true

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

      - name: Bootstrap Hamlib build system
        run: ./bootstrap

      - name: Configure Hamlib
        run: |
          ./configure --prefix=/d/a/js8call/hamlib-install

      - name: Build Hamlib
        run: |
          make
          pwd
          
      - name: Install Hamlib
        run: make install-strip

      - name: Upload Hamlib binaries
        uses: actions/upload-artifact@v4
        with:
          name: hamlib-windows-msys2-binaries
          path: "D:/a/js8call/hamlib-install/"

  create_and_upload:
    name: Create GitHub Release
    needs: build-hamlib-windows-msys2
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hamlib-windows-msys2-binaries
          path: my-artifact/ # Path to save the downloaded artifact

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          target_commitish: ${{ github.ref }}
          files: |
            my-artifact/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
