name: Build Hamlib SDK on Windows (MSYS2)

on:
  push:
    branches:
      - build-artifacts

jobs:
  build-windows-msys2:
    runs-on: windows-2025

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'Hamlib/Hamlib.git'
          ref: '4.6.4' 
          fetch-depth: 0 
          persist-credentials: false
          submodules: recursive
          lfs: true
          clean: true

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

      - name: Bootstrap Hamlib build system
        run: ./bootstrap

      - name: Configure Hamlib
        run: |
          ./configure --prefix=/c/hamlib-install

      - name: Build Hamlib
        run: |
          make
          tar cf /c/a/js8call/hamlib-windows-msys2-binaries.tar .      
          find /c/a/js8call/ -name hamlib-windows-msys2-binaries.tar -print
          
 #     - name: Install Hamlib
 #       run: make install-strip

      - name: Upload Hamlib binaries
        uses: actions/upload-artifact@v4
        with:
          name: hamlib-windows-msys2-binaries
          path: "C:a/js8call/hamlib-windows-msys2-binaries.tar"
          retention-days: 30
