permissions:
  contents: read

name: CI Build for Linux x86_64 and Arm64

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  build_package: build-essential git cmake libusb-1.0-0-dev libxkbcommon-dev libudev-dev
  ffmpeg_package: ffmpeg libavformat-dev libavcodec-dev libavutil-dev libswresample-dev libpulse-dev
  opengl_package1: libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libgl1-mesa-dev libxkbcommon-x11-dev 
  opengl_package2: libxcb-keysyms1-dev libxcb-image0-dev libxcb-icccm4-dev libxcb-render-util0-dev 
  opengl_package3: libxcb-xfixes0-dev libxcb-sync-dev libxcb-randr0-dev libxrender-dev

#  appimg_package: libfuse2 imagemagick
#  qt_package: qt6-base-dev qt6-multimedia-dev qt6-serialport-dev
#  misc_package: libhamlib-dev libfftw3-dev libboost-all-dev 


jobs:
  build_amd64_2404:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install dependencies (ubuntu)
      run: |
        sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7
        sudo apt-get update
        sudo apt-get install -y ${{ env.build_package }} ${{ env.ffmpeg_package }} ${{ env.opengl_package1 }} ${{ env.opengl_package2 }} ${{ env.opengl_package3 }}
        ffmpeg -version

# For CI, these should really already be built somewhere or cached
    - name: Cache Hamlib 4.6.4
      id: cache-hamlib
      uses: actions/cache@v4
      with:
        path: ${GITHUB_WORKSPACE}/local/hamlib
        key: ${{ runner.os }}-${{ env.ImageOS }}-${{ runner.arch }}-hamlib

    - name: Install Hamlib 4.6.4
      if: steps.cache-hamlib.outputs.cache-hit != 'true'
      id: install-hamlib
      run: |
        git clone https://github.com/Hamlib/Hamlib.git ~/hamlib
        cd ~/hamlib
        git checkout 4.6.4
        ./bootstrap
        ./configure --prefix=${GITHUB_WORKSPACE}/local/hamlib
        make -j 4
        sudo make install-strip
        sudo ldconfig
 
    - name: Cache fftw 3.3.10
      id: cache-fftw
      uses: actions/cache@v4
      with:
        path: ${GITHUB_WORKSPACE}/local/fftw
        key: ${{ runner.os }}-${{ env.ImageOS }}-${{ runner.arch }}-fftw

    - name: Install fftw 3.3.10
      if: steps.cache-fftw.outputs.cache-hit != 'true'
      id: install-fftw
      run: |
        curl --location --output ./fftw-3.3.10.tar.gz https://www.fftw.org/fftw-3.3.10.tar.gz
        tar zxf fftw-3.3.10.tar.gz
        cd fftw-3.3.10
        ./configure --prefix=${GITHUB_WORKSPACE}/local/fftw
        make
        sudo make install
    
    - name: Cache Boost 1.88
      id: cache-boost
      uses: actions/cache@v4
      with:
        path: ${GITHUB_WORKSPACE}/local/boost
        key: ${{ runner.os }}-${{ env.ImageOS }}-${{ runner.arch }}-boost

    - name: Install Boost 1.88
      if: steps.cache-boost.outputs.cache-hit != 'true'
      id: install-boost
      run: |
        curl --location --output ./boost-1.88.0.tar.gz https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
        tar zxf boost-1.88.0.tar.gz
        cd boost_1_88_0
        ./bootstrap.sh --prefix=${GITHUB_WORKSPACE}/local/boost
        sudo ./b2 install

    - name: Cache QT 6.8.3
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${GITHUB_WORKSPACE}/qt683-install
        key: ${{ runner.os }}-${{ env.ImageOS }}-${{ runner.arch }}-qt683

    - name: Find libavcodec.pc
      run: sudo find ${GITHUB_WORKSPACE}/ -name libavcodec.pc -print

    # Takes about 1 hour, this one should definitely be pre-built
    - name: Install QT 6.8.3
      if: steps.cache-qt.outputs.cache-hit != 'true'
      id: install-qt683
      run: |
        git clone https://github.com/qt/qt5.git qt6
        cd qt6
        git switch 6.8.3
        mkdir -p qt6/build
        cd qt6/build
        ls -l ..
        ${GITHUB_WORKSPACE}/qt6/configure -DCMAKE_FIND_DEBUG_MODE=1 --prefix=${GITHUB_WORKSPACE}/qt683-install -init-submodules -submodules qtmultimedia,qtserialport
        cmake --build .
        cmake --install .

    - name: QT 6.8.3 Summary
      run: cat ${GITHUB_WORKSPACE}/qt6/qt6/build/config.summary
      
    - name: Check disk space
      run: df -h /
      
    - name: Build JS8Call 
      run: |
        pwd
        mkdir -p build && cd build
        cmake -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/qt683-install;${GITHUB_WORKSPACE}/local/" ..
        make -j 4
