permissions:
  contents: read

name: EXPERIMENTAL Build for Windows using new cmakelists

on:
  push:
    branches: [ "main" ]
    paths:
      '.github/workflows/new-cmake-win64.yml'
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_windows-2025:
    runs-on: windows-2025
    permissions: write-all

    steps:
    - run: git config --global core.autocrlf input
    - run: git clone -b fix/cmake https://github.com/bazineta/js8call.git
    - run: cat js8call/CMakeLists.txt
           
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git python base-devel make unzip zip tar
        pacboy: >-
          toolchain:p
          autotools:p
          cmake:p
          ninja:p
          libusb:p
          wget:p
          boost:p
          fftw:p
          sqlite3:p
          nsis:p

    - name: Setup build directories
      shell: msys2 {0}
      run: |
        mkdir -p js8call/build

    - name: Release download for QT6
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'wmiler/js8call'
        fileName: 'qt663-windows-msys2-binaries*.zip'
        tag: 'qt6-v6.6.3-ci'
        extract: true
        out-file-path: 'D:/a/_temp/msys64/mingw64/'

    - name: Release download for hamlib
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'wmiler/js8call'
        fileName: 'hamlib-windows-msys2-binaries*.zip'
        tag: 'hamlib-v4.6.4-ci'
        extract: true
        out-file-path: 'D:/a/_temp/msys64/mingw64/'
       
# Below is the workaround for installing OmniRig on the Github runners
# which is just everything in Program Files (86)\Afreet directory plus the reg file.
    - name: Fetch OmniRig.tar.gz from my site
      run: |
        Invoke-WebRequest -Uri "https://www.spacemonitoring.com/OmniRig120.tar.gz" -OutFile ".\OmniRig120.tar.gz"
        Invoke-WebRequest -Uri "https://www.spacemonitoring.com/OmniRig120.reg" -OutFile ".\OmniRig120.reg"

    - name: Untar to Program Files (x86)
      run: tar -xzf ".\OmniRig120.tar.gz" -C "C:\"

    - name: Add registry entries so OmniRig cmake works
      run: |
        reg import .\OmniRig120.reg

# The issue is NO install() directives in the new CMakeLists.txt!
# Will need to sed changes in for now to give the Windows build a place 
# to install into. Leaving the debug stuff in place for now.

    - name: Create install.cmake 
      run: |
        cd ./js8call/
        touch CMake/Modules/install.cmake
        cat > CMake/Modules/install.cmake << EOF
          if (WIN32)
            set (PLUGIN_DESTINATION plugins)
          if (WSJT_CREATE_WINMAIN)
            set_target_properties (js8call PROPERTIES WIN32_EXECUTABLE ON)
          endif (WSJT_CREATE_WINMAIN)
            install (CODE "
              get_filename_component (the_qt_conf \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${WSJT_QT_CONF_DESTINATION}/qt.conf\" REALPATH)
              file (WRITE \"\${the_qt_conf}\" \"[Paths] \")"
              #COMPONENT runtime
              )

              # if a system Qt is used (e.g. installed in /usr/lib/), it will not be included in the installation
              set (fixup_exe "\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/${CMAKE_PROJECT_NAME}${CMAKE_EXECUTABLE_SUFFIX}")

              get_filename_component (hamlib_lib_dir ${Hamlib_LIBRARY} PATH)
              list (APPEND fixup_library_dirs ${hamlib_lib_dir}/../bin)

              get_filename_component (usb_lib_dir ${Usb_LIBRARY} PATH)
              list (APPEND fixup_library_dirs ${usb_lib_dir})

              get_filename_component (fftw_lib_dir ${FFTW3F_LIBRARY} PATH)
              list (APPEND fixup_library_dirs ${fftw_lib_dir})

              install (
              	DIRECTORY
              	${QT_PLUGINS_DIR}/platforms
               	${QT_PLUGINS_DIR}/accessible
              	${QT_PLUGINS_DIR}/audio
               	${QT_PLUGINS_DIR}/imageformats
                ${QT_PLUGINS_DIR}/styles
               	DESTINATION ${WSJT_PLUGIN_DESTINATION}
              	CONFIGURATIONS Release MinSizeRel RelWithDebInfo
              	#COMPONENT runtime
                FILES_MATCHING PATTERN "*${CMAKE_SHARED_LIBRARY_SUFFIX}"
                PATTERN "*minimal*${CMAKE_SHARED_LIBRARY_SUFFIX}" EXCLUDE
                PATTERN "*offscreen*${CMAKE_SHARED_LIBRARY_SUFFIX}" EXCLUDE
                PATTERN "*quick*${CMAKE_SHARED_LIBRARY_SUFFIX}" EXCLUDE
                PATTERN "*d${CMAKE_SHARED_LIBRARY_SUFFIX}" EXCLUDE
            	)
              file (RELATIVE_PATH _plugins_path "${CMAKE_INSTALL_PREFIX}/${WSJT_QT_CONF_DESTINATION}" "${CMAKE_INSTALL_PREFIX}/${WSJT_PLUGIN_DESTINATION}")
              install (CODE "
                get_filename_component (the_qt_conf \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${WSJT_QT_CONF_DESTINATION}/qt.conf\" REALPATH)
                file (APPEND \"\${the_qt_conf}\" \"Plugins = ${_plugins_path}\")"
              	#COMPONENT runtime
            	)

              set (gp_tool "objdump")	# we want MinGW tool - not MSVC (See GetPrerequisites.cmake)
              install (CODE "
               get_filename_component (the_path \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${WSJT_PLUGIN_DESTINATION}\" REALPATH)
               file (GLOB_RECURSE QTPLUGINS \"\${the_path}/*${CMAKE_SHARED_LIBRARY_SUFFIX}\")
               set (CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/CMake/Modules ${CMAKE_MODULE_PATH})
               include (BundleUtilities)
               set (BU_CHMOD_BUNDLE_ITEMS ON)
               set (gp_tool ${gp_tool})
               # canonicalize path in install context
               get_filename_component (the_exe ${fixup_exe} REALPATH)
               fixup_bundle (\"\${the_exe}\" \"\${QTPLUGINS}\" \"${fixup_library_dirs}\")"
               #COMPONENT runtime
               )
        EOF

    - name: Edit CMakeLists.txt to add verbose for windeployqt and include the install.cmake
      run: |
        cd ./js8call/
        cat CMake/Modules/install.cmake

    - name: Edit CMakeLists.txt to add verbose for windeployqt and include the install.cmake
      run: |
        cd ./js8call/
        sed -i '471i/include(CMake/Modules/install.cmake)'
        sed -i 's#COMMAND "${WINDEPLOYQT}" "$<TARGET_FILE_DIR:${TARGET}>"#COMMAND "${WINDEPLOYQT}" --verbose 2 "$<TARGET_FILE_DIR:${TARGET}>"#' CMakeLists.txt

    - name: Edit NSIS.template.in to add verbose
      run: |
        cd ./js8call/
        sed -i '1i!verbose 4' CMake/Modules/NSIS.template.in
      
    - name: Configure JS8Call
      shell: msys2 {0}
      run: |
        cd ./js8call/build
        cmake -G "MinGW Makefiles" ..
        # cmake -DENABLE_OMNIRIG=ON -G "MinGW Makefiles" ..

    - name: Build JS8Call
      shell: msys2 {0}
      run: |
        cd ./js8call/build
        cmake --build . --config Release
      continue-on-error: true

    - name: Package JS8Call
      shell: msys2 {0}
      run: |
        cd ./js8call/build
        cmake --build . --config Release --target package --verbose
      continue-on-error: true
      
    - name: Build directory listing and CPackConfig/SourceConfig
      run: |
        dir "D:/a/js8call/js8call/js8call/build/"
        cat "D:/a/js8call/js8call/js8call/build/CPackConfig.cmake"
        cat "D:/a/js8call/js8call/js8call/build/CPackSourceConfig.cmake"
      continue-on-error: true
      
    - name: NSIS Error logs (Output)
      run: |
        cat "D:/a/js8call/js8call/js8call/build/_CPack_Packages/win64/NSIS/NSISOutput.log"
      continue-on-error: true

    - name: NSIS Error logs (Project)
      run: |
        cat "D:/a/js8call/js8call/js8call/build/_CPack_Packages/win64/NSIS/project.nsi"
      continue-on-error: true

    - name: NSIS directory listings
      run: |
        dir "D:/a/js8call/js8call/js8call/build/_CPack_Packages/win64/"
        dir "D:/a/js8call/js8call/js8call/build/_CPack_Packages/win64/NSIS/"
        dir "D:/a/js8call/js8call/js8call/build/_CPack_Packages/win64/NSIS/JS8Call-2.3.1-win64/"
      continue-on-error: true
      
    - name: Upload Artifact (from github runner)
      uses: actions/upload-artifact@v4
      with:
        name: js8call-2.3.2-devel-win64.exe
        path: "build/js8call-2.3.2-devel-win64.exe"

# This doesn't work if we keep commiting to the same tag, need to add a bit of if/else.
# For now, continue-on-error is enabled. This should be able to go away on the 
# main js8call/js8call repo and work with regular commit sha.
    - name: Create GitHub Release and get short commit SHA
      id: get_sha
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Create Git Tag
      id: create_tag
      uses: actions/github-script@v8
      with:
        script: |
          const shortSha = process.env.SHORT_SHA;
          const tagName = `cmake-js8call-v2.3.2-devel-ci`;
            
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${tagName}`,
            sha: context.sha,
          });
          console.log(`Tag '${tagName}' created.`);
      env:
        SHORT_SHA: ${{ steps.get_sha.outputs.short_sha }}
      continue-on-error: true

    - name: Create zip file to upload to release page
      shell: msys2 {0}
      run: |
        cd build
        zip -r "../js8call-2.3.2-devel-win64.exe-ci.zip" "js8call-2.3.2-devel-win64.exe"
      continue-on-error: true
         
    - name: Create Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        mode: "COMMIT"
        configurationJson: |
          {
            "template": "#{{CHANGELOG}}",
            "categories": [
              {
                  "title": "## Feature",
                  "labels": ["feat", "feature"]
              },
              {
                  "title": "## Fix",
                  "labels": ["fix", "bug"]
              },
              {
                  "title": "## Other",
                  "labels": []
              }
            ],
            "label_extractor": [
              {
                "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                "on_property": "title",
                "target": "$1"
              }
            ]
          }
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.3.3
      with:
        tag_name: js8call-v2.3.2-devel-ci
        name: "JS8Call v2.3.2-devel Windows MSYS2 CI Github runner build ${{ steps.get_sha.outputs.short_sha }}"
        body: |
          ** EXPERIMENTAL CMake build **
          Release created automatically from commit ${{ github.sha }}.
          This release is from the Windows MSYS2 CI builds via Github runner for JS8Call. Use at your own risk!
          ${{steps.github_release.outputs.changelog}}
        files: js8call-2.3.2-devel-win64.exe-ci.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
