name: Install OmniRig
on:
  push:
    branches: [ main ]
    paths:
      '.github/workflows/omnirig-test.yml'    
  pull_request:
    branches: [ main ]
    paths:
      '.github/workflows/omnirig-test.yml'
      
jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Fetch OmniRig.tar.gz from my site
        run: Invoke-WebRequest -Uri "https://www.spacemonitoring.com/OmniRig120.tar.gz" -OutFile ".\OmniRig120.tar.gz"

      - name: Directory
        run:
          dir

      - name: Untar to Program Files (x86)
        run: tar -xzf ".\OmniRig120.tar.gz" -C "C:\"
