name: Install OmniRig
on:
  push:
    branches: [ main ]
    paths:
      '.github/workflows/omnirig-test.yml'    
  pull_request:
    branches: [ main ]
    paths:
      '.github/workflows/omnirig-test.yml'
      
jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Fetch OmniRig.tar.gz from my site
        run: Invoke-WebRequest -Uri "https://www.spacemonitoring.com/OmniRig120.tar.gz"

      - name: Directory
        run:
          dir

      - name: Untar to Program Files (x86)
        run: Expand-Archive -Path ".\OmniRig120.tar.gz" -DestinationPath "C:\" -Force
