name: Build QT 6.6.3 on Windows (MSYS2)

on:
  push:
    branches:
      - build-artifacts
    paths:
      '.github/workflows/qt663-msys.yml'

jobs:
  build-qt663-windows-msys2:
    runs-on: windows-2025

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

      - name: Checkout QT 6.6.3
        run: |
          pwd
          git clone https://github.com/qt/qt5.git qt6
          cd qt6
          git switch 6.6.3
          ./init-repository --module-subset=essential,qtactiveqt,qtmultimedia,qtserialport,qtsvg,qtshadertools,qttools
          mkdir ./build
          cd build
          ../configure --prefix=/d/a/js8call/qt663-install
          
      - name: Build QT 6.6.3
        run: |
          pwd
          cd qt6/build
          cmake --build . --parallel 4
          cmake --install .
          ls -l /d/a/
          ls -l /d/a/js8call
          ls -l /d/a/js8call/js8call

      - name: Upload QT 6.6.3 binaries
        uses: actions/upload-artifact@v4
        with:
          name: qt663-windows-msys2-binaries
          path: /d/a/js8call/qt663-install/          
