name: Build QT 6.6.3 on Windows (MSYS2)

on:
  push:
    branches: [ "main" ]
    paths:
      '.github/workflows/qt663-msys.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-qt663-windows-msys2:
    runs-on: windows-2025
    permissions: write-all
    
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
            tar
            zip
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

#      - name: Check for directories here, so we fail fast
#        run: |
#          pwd
#          ls -l "D:/a/js8call/"
#          ls -l "D:/a/js8call/js8call"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'qt/qt5.git'
          ref: '6.6.3'
          fetch-depth: 0 
          persist-credentials: false
          submodules: recursive
          lfs: true
          clean: true
          
      - name: Checkout QT 6.6.3
        run: |
          git clone https://github.com/qt/qt5.git qt6
          cd qt6
          git switch 6.6.3
          ./init-repository --module-subset=essential,qtactiveqt,qtmultimedia,qtserialport,qtsvg,qtshadertools,qttools

      - name: Configure QT
        run: |
          ls -l
          mkdir ./build
          cd build
          ../configure --prefix=/d/a/js8call/qt663-install
          
      - name: Build QT 6.6.3
        run: |
          cd build
          cmake --build . --parallel 4
          cmake --install .
    
      - name: Create zip file to upload to release page
        shell: pwsh
        run: |
          pwd
          Compress-Archive -Path "D:\a\js8call\qt663-install\" -DestinationPath "D:\a\js8call\qt663-windows-msys2-binaries.zip"
          ls -l "D:/a/js8call/js8call/"
          ls -l "D:/a/js8call/"
        continue-on-error: true

      - name: Upload QT 6.6.3 Artifact binaries
        uses: actions/upload-artifact@v4
        with:
          name: qt663-windows-msys2-binaries
          path: /d/a/js8call/qt663-install/
          
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: qt6-v6.6.3-ci
          name: "QT6 v6.6.3 for Windows MSYS2 CI build"
          body: |
            Release created automatically from commit.
            This release is for use in the Windows MSYS2 CI builds for JS8Call. Use at your own risk!
          files: "D:\\a\\js8call\\qt663-windows-msys2-binaries.zip"
#          files: "D:/a/js8call/js8call/qt663-windows-msys2-binaries.zip"
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
