name: Build QT 6.6.3 on Windows (MSYS2)

on:
  push:
    branches: [ "main" ]
    paths:
      '.github/workflows/qt663-msys.yml'

jobs:
  build-qt663-windows-msys2:
    runs-on: windows-2025
    permissions: write-all
    
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

      - name: Checkout QT 6.6.3
        run: |
          pwd
          git clone https://github.com/qt/qt5.git qt6
          cd qt6
          git switch 6.6.3
          ./init-repository --module-subset=essential,qtactiveqt,qtmultimedia,qtserialport,qtsvg,qtshadertools,qttools
          mkdir ./build
          cd build
          ../configure --prefix=/d/a/js8call/qt663-install
          
      - name: Build QT 6.6.3
        run: |
          pwd
          cd qt6/build
          cmake --build . --parallel 4
          cmake --install .
          ls -lh .

      - name: Create zip file to upload to release page
        run: |
          pwd
          cd qt6/build
          zip -r /d/a/js8call/js8call/qt663-windows-msys2-binaries.zip .
          ls -lh .

      - name: Upload QT 6.6.3 binaries
        uses: actions/upload-artifact@v4
        with:
          name: qt663-windows-msys2-binaries
          path: /d/a/js8call/qt663-install/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: v6.6.3
          name: "QT6 v6.6.3 for Windows MSYS2 CI build"
          prerelease: false
          make-latest: true
          body: |
            Release created automatically from commit.
            This release is for use in the Windows MSYS2 CI builds for JS8Call. Use at your own risk!
          files: /d/a/js8call/js8call/qt663-windows-msys2-binaries.zip
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
