name: Build QT 6.6.3 on Windows (MSYS2)

on:
  push:
    branches:
      - build-artifacts
    paths:
      '.github/workflows/qt663-msys.yml'

jobs:
  build-qt663-windows-msys2:
    runs-on: self-hosted

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true 
          install: > 
            git 
            make 
            base-devel
            autoconf 
            libtool 
            pkg-config
          pacboy: >-
            toolchain:p
            autotools:p
            cmake:p
            ninja:p
            libusb:p

      - name: Checkout QT 6.6.3
        run: |
          pwd
          git clone https://github.com/qt/qt5.git qt6
          mkdir /c/actions-runner/_work/js8call/js8call/js8libs
          cd qt6
          git switch 6.6.3
          ./init-repository --module-subset=essential,qtactiveqt,qtmultimedia,qtserialport,qtsvg
          mkdir ./build
          cd build
          ../configure -prefix /c/actions-runner/_work/js8call/js8call/js8libs

      - name: Build QT 6.6.3
        run: |
          pwd
          cd qt6/build
          cmake --build . --parallel
          pwd

          tar cf /c/actions-runner/_work/js8call/qt663-windows-msys2-binaries.tar .      
#          find /d/a/js8call/ -name qt663-windows-msys2-binaries.tar -print
          
      - name: Upload QT 6.6.3 binaries
        uses: actions/upload-artifact@v4
        with:
          name: qt663-windows-msys2-binaries
          path: "C:/actions_runner/_work/js8call/qt663-windows-msys2-binaries.tar"
          retention-days: 7
          
