name: Build QT 6.6.3 on MacOS

on:
  push:
    branches:
      - build-artifacts
    paths:
      '.github/workflows/qt681-mac.yml'

jobs:
  build-qt663-mac:
    runs-on: macos-15

    steps:
    - name: Install CMake
      run: |
        brew update
        brew install cmake
        
    - name: Install Ninja
      run: brew install ninja

    - name: Install libusb
      run: |
        df -h /
        brew install libusb

    - name: Checkout QT 6.6.3
      run: |
        pwd
        git clone https://github.com/qt/qt5.git qt6
        cd qt6
        git switch 6.6.3
        ./init-repository --module-subset=essential,qtmultimedia,qtserialport,qtsvg,qtshadertools,qttools
        mkdir ./build
        
    - name: Configure QT 6.6.3
      run: |
        cd qt6/build
        ../configure --prefix=/Users/runner/work/js8call/qt663-install
        df -h /
          
    - name: Build QT 6.6.3
      run: |
        pwd
        cd qt6/build
        cmake --build . --parallel 4
        cmake --install .

    - name: Upload QT 6.6.3 binaries
      uses: actions/upload-artifact@v4
      with:
        name: qt663-macos-binaries
        path: /Users/runner/work/js8call/qt663-install/          
